apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lukin-me
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lukin.me
        - www.lukin.me
      secretName: lukin-me-tls
  rules:
    - host: lukin.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lukin-me
                port:
                  number: 80

